#!/bin/bash

declare -a repos=(
    "eslint-buildkite-plugin"
    "check-colours-buildkite-plugin"
)

for i in "${repos[@]}"
do
   echo "------ $i"
   git fetch "$i"
   git subtree pull --prefix=plugins/$i/ "$i" master --squash
done

# References:
# - https://www.atlassian.com/blog/git/alternatives-to-git-submodule-git-subtree
